### ISSUE TITLE
Wierd output with vertices in the negative axes

### ISSUE THREAD

**Issue by liuchao3-bgi** [davidackerman/multiresolution-mesh-creator#1]
Hi, I ran into some problems when I tried to create my own multi-res meshes. It seems that the creator now can only deal with meshes whose vertices are all in the positive axes. In the following figure, the red one is my original mesh, the area below 0 are not shown. I have to rezero (using trimesh pkg) the mesh myself to make it generate the mesh properly (the blue one), but I have to remember the offset to make the mesh and the volume data aligned. Is there a way to make this fantastic tool to work with negative vertices?

![image](https://user-images.githubusercontent.com/95390642/145754209-30fa3305-809f-4770-b747-01da709918a3.png)

**Comment by davidackerman** [comment]
You are correct, up until this point I assumed all meshes would have positive vertices. I have now updated the code to allow for negative vertices. Let me know if you still have issues. Thanks for pointing this out!

**Comment by liuchao3-bgi** [comment]
Problem solved！Thanks a million.

![image](https://user-images.githubusercontent.com/95390642/145958310-33b425ef-bf5f-4678-be6d-7f1cd6971701.png)
